// Generated by CoffeeScript 1.6.2
var timebar;

Reveal.initialize({
  controls: true,
  keyboard: true,
  progress: true,
  overview: true,
  transition: 'linear',
  dependencies: [
    {
      src: 'js/highlight.js',
      async: true,
      callback: function() {
        return hljs.initHighlightingOnLoad();
      }
    }, {
      src: 'js/showdown.js',
      condition: function() {
        return !!document.querySelector('[data-markdown]');
      }
    }, {
      src: 'js/markdown.js',
      condition: function() {
        return !!document.querySelector('[data-markdown]');
      }
    }
  ]
});

timebar = document.getElementById('timebar');

Reveal.addEventListener('slidechanged', function(e) {
  var TOTAL_TIME, onTick, tick;

  if (e.indexh === 1 && e.indexv === 0) {
    TOTAL_TIME = 600;
    tick = 0;
    onTick = function() {
      var width;

      if (tick <= TOTAL_TIME) {
        width = tick / TOTAL_TIME * window.innerWidth;
        timebar.style.width = "" + width + "px";
        return tick += 1;
      }
    };
    return setInterval(onTick, 1000);
  }
});
